import carImg1 from '../assets/car1.png';
import carImg7 from '../assets/car7.png';

const cars = [
    {
      name: "Koenigsegg",
      type: "Sport",
      image:carImg1 ,
      fuel: "90L",
      transmission: "Manual",
      capacity: "2 People",
      price: "$99.00",
      oldPrice: "",
    },
    {
      name: "Nissan GT - R",
      type: "Sport",
      image: carImg1,
      fuel: "80L",
      transmission: "Manual",
      capacity: "2 People",
      price: "$80.00",
      oldPrice: "$100.00",
    },
    {
      name: "Rolls - Royce",
      type: "Sedan",
      image: carImg1,
      fuel: "70L",
      transmission: "Manual",
      capacity: "4 People",
      price: "$96.00",
      oldPrice: "",
    },
    {
      name: "Nissan GT - R",
      type: "Sport",
      image:carImg1,
      fuel: "80L",
      transmission: "Manual",
      capacity: "2 People",
      price: "$80.00",
      oldPrice: "$100.00",
    },
    {
        name: "All New Rush",
        type: "SUV",
        image:carImg7,
        fuel: "70L",
        transmission: "Manual",
        capacity: "6 People",
        price: "$72.00",
        oldPrice: "$80.00",
      },
      {
        name: "CR-V",
        type: "SUV",
        image:carImg7,
        fuel: "80L",
        transmission: "Manual",
        capacity: "6 People",
        price: "$80.00",
        oldPrice: "",
      },
      {
        name: "All New Terios",
        type: "SUV",
        image:carImg7,
        fuel: "90L",
        transmission: "Manual",
        capacity: "6 People",
        price: "$74.00",
        oldPrice: "",
      },
      {
        name: "CR-V",
        type: "SUV",
        image:carImg7,
        fuel: "80L",
        transmission: "Manual",
        capacity: "6 People",
        price: "$80.00",
        oldPrice: "",
      },
      {
        name: "MG ZX Exclusice",
        type: "Hatchback",
        image:carImg7,
        fuel: "70L",    
        transmission: "Manual",
        capacity: "4 People",
        price: "$76.00",
        oldPrice: "$80.00",
      },
      {
        name: "New MG ZS",
        type: "SUV",
        image:carImg7,
        fuel: "80L",    
        transmission: "Manual",
        capacity: "6 People",
        price: "$80.00",
        oldPrice: "",
      },
      {
        name: "MG ZX Excite",
        type: "Hatchback",
        image:carImg7,
        fuel: "90L",    
        transmission: "Manual",
        capacity: "4 People",
        price: "$76.00",
        oldPrice: "",
      },
      {
        name: "New MG ZS",
        type: "SUV",
        image:carImg7,
        fuel: "80L",    
        transmission: "Manual",
        capacity: "6 People",
        price: "$80.00",
        oldPrice: "",
      },
  ];
  
export default cars;